---
- name: mkdir install dir
  become: yes
  become_user: root
  with_items:
    - '{{ calico_cni_install_target_dir }}'
    - '{{ calico_cni_install_dir }}'
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
    
- name: download...
  become: yes
  become_user: root
  with_items: '{{ calico_cni_binaries[calico_cni_ver] }}'
  get_url:
    url: '{{ calico_cni_url }}/{{ item.f }}-{{ calico_cni_platform }}'
    dest: '{{ calico_cni_install_target_dir }}/{{ item.f }}'
    checksum: '{{ item.checksums[calico_cni_platform] }}'
    mode: 0755

- name: linking...
  become: yes
  become_user: root
  with_items: '{{ calico_cni_binaries[calico_cni_ver] }}'
  file:
    src: '{{ calico_cni_install_target_dir }}/{{ item.f }}'
    dest: '{{ calico_cni_install_dir }}/{{ item.f }}'
    state: link
