---
- name: mkdir install dir
  become: yes
  become_user: root
  file:
    path: '{{calico_cni_install_dir}}'
    state: directory
    mode: '0755'
    
- name: download...
  become: yes
  become_user: root
  with_items: '{{calico_cni_binaries}}'
  get_url:
    url: '{{calico_cni_url}}/{{item.f}}'
    dest: '{{calico_cni_install_dir}}/{{item.f}}'
    checksum: '{{item.checksum}}'
    mode: '0755'

- name: linking...
  become: yes
  become_user: root
  with_items: '{{calico_cni_binaries}}'
  file:
    src: '{{calico_cni_install_dir}}/{{item.f}}'
    dest: '{{calico_cni_install_parent_dir}}/{{item.f}}'
    state: link

